### ISSUE TITLE
Template "About" and "Copyright" pages

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire-docs#7]
In previous iterations, we created multiple shortcodes so that users could put together custom About and Copyright pages. However, it was 4 or 5 unique shortcodes and none of them have much use elsewhere outside these pages. So, better to create an `about` page type and build everything into the template. Should also then include a variant `copyright` class or layout option to account for the differences between how this information is typically handled online versus in print.

**Comment by geealbers** [comment]
Based on what we've done in previous publications, we may need to add some attributes to the Quire content model and to `publication.yml`:

```yaml
publisher:
  address:
distribution:
illustration_credits:
  online:
  pdf_ebook:
```
